site_name: Readm's Blog
theme:
  locale: zh_CN
  name: readthedocs
  highlightjs: true
  navigation_depth: 4
  collapse_navigation: True
  title_only: True
  analytics:
        gtag: G-ET7BC0JY44

plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - tables
